### ISSUE TITLE
No List of Supported Distros

### ISSUE THREAD

**Issue by mattouille** [anchore/anchore#48]
I recently came across a message while implementing anchore that states that Debian 8 is not a supported distro. This is of course [not the case](https://wiki.debian.org/LTS) as it's supported until 2020, so I assume Anchore is saying _it_ doesn't support Debian 8.

The message I see is while running Anchore in local mode through Jenkins.

Gate: ANCHORESEC
Trigger: UNSUPPORTEDDISTRO
Check Output: cannot perform CVE scan: no CVE data is currently available for the detected base distro type (debian:8)

I am available in IRC if anyone wants to talk about this further.

**Comment by nurmi** [comment]
Hi Matt!

The CVE scan requires that anchore has been called with a 'anchore feeds sync' at least once, which pulls down the latest vulnerability data for all of the distro/versions that anchore supports.  Once the data is available, you should be able to scan that image for vulnerabilities.  Also, when you perform a 'anchore feeds sync' operation, you'll see in the output the full list of distro/versions that are supported by anchore:

```
# anchore feeds sync
syncing data for subscribed feed (vulnerabilities) ...
	syncing group data: debian:unstable: ...
	syncing group data: ubuntu:16.04: ...
	syncing group data: centos:6: ...
	syncing group data: centos:7: ...
	syncing group data: centos:5: ...
	syncing group data: ubuntu:14.10: ...
	syncing group data: ubuntu:15.04: ...
	syncing group data: debian:9: ...
	syncing group data: debian:8: ...
	syncing group data: ubuntu:12.04: ...
	syncing group data: ubuntu:17.10: ...
	syncing group data: debian:7: ...
	syncing group data: ubuntu:16.10: ...
	syncing group data: alpine:3.3: ...
	syncing group data: alpine:3.4: ...
	syncing group data: alpine:3.5: ...
	syncing group data: alpine:3.6: ...
	syncing group data: ol:6: ...
	syncing group data: ubuntu:14.04: ...
	syncing group data: ubuntu:15.10: ...
	syncing group data: ubuntu:12.10: ...
	syncing group data: ubuntu:17.04: ...
	syncing group data: ol:7: ...
	syncing group data: ubuntu:13.04: ...
	syncing group data: ol:5: ...
#
```
Let us know how it goes - and/or we'll chat further on slack!

Best,
-Dan

**Comment by mattouille** [comment]
That makes sense. The Jenkins local documentation seems to be lacking in that instruction, but maybe that was assumed.

**Comment by nurmi** [comment]
Matt,

Interesting - the container we use for Jenkins (anchore/jenkins:latest) does an initial sync on build, so it shouldn't be required if you're using that container (the default, if you're using the plugin) - however - I just checked the container and it looks like there was a failure to sync debian:8 on the last build of the container that wasn't caught, which explains why that one in particular is failing (it does periodically sync, so it would eventually sync debian:8, but we want for a base set to be present in the container for the get-go).  Great catch - I've built and pushed a new container that has all the distros properly synced just now, as anchore/jenkins:latest.

If you decide to go with anchore-engine, it also syncs the data automatically, when it starts up, so you shouldn't have to manually run a sync there either.

Best,
-Dan

**Comment by zhill** [comment]
If you need to debug the feed state you can dump a listing of what has been synced (this is from inside a container, you can run it with docker exec on the anchore/jenkins container if needed):
```
[root@d13314bdaad2 /]# anchore feeds list
Subscribed:
  vulnerabilities:
    description: This feed provides vulnerability data for various linux distributions
      in json form
Unavailable/Insufficient Access Tier:
  packages:
    description: This feed provides package data for various application package systems
      in json form
[root@d13314bdaad2 /]# anchore feeds show vulnerabilities
access_tier: 0
description: This feed provides vulnerability data for various linux distributions
  in json form
groups:
  alpine:3.3:
    access_tier: 0
    description: This group provides the vulnerability data for alpine:3.3
    last_sync: '2017-11-15T17:56:08'
  alpine:3.4:
    access_tier: 0
    description: This group provides the vulnerability data for alpine:3.4
    last_sync: '2017-11-15T17:56:09'
  alpine:3.5:
    access_tier: 0
    description: This group provides the vulnerability data for alpine:3.5
    last_sync: '2017-11-15T17:56:11'
  alpine:3.6:
    access_tier: 0
    description: This group provides the vulnerability data for alpine:3.6
    last_sync: '2017-11-15T17:56:12'
  centos:5:
    access_tier: 0
    description: This group provides the vulnerability data for centos:5
    last_sync: '2017-11-15T17:55:41'
  centos:6:
    access_tier: 0
    description: This group provides the vulnerability data for centos:6
    last_sync: '2017-11-15T17:55:38'
  centos:7:
    access_tier: 0
    description: This group provides the vulnerability data for centos:7
    last_sync: '2017-11-15T17:55:40'
  debian:7:
    access_tier: 0
    description: This group provides the vulnerability data for debian:7
    last_sync: '2017-11-15T17:56:01'
  debian:8:
    access_tier: 0
    description: This group provides the vulnerability data for debian:8
    last_sync: '2017-11-15T17:55:51'
  debian:9:
    access_tier: 0
    description: This group provides the vulnerability data for debian:9
    last_sync: '2017-11-15T17:55:45'
  debian:unstable:
    access_tier: 0
    description: This group provides the vulnerability data for debian:unstable
    last_sync: '2017-11-15T17:55:29'
  ol:5:
    access_tier: 0
    description: This group provides the vulnerability data for ol:5
    last_sync: '2017-11-15T17:56:40'
  ol:6:
    access_tier: 0
    description: This group provides the vulnerability data for ol:6
    last_sync: '2017-11-15T17:56:13'
  ol:7:
    access_tier: 0
    description: This group provides the vulnerability data for ol:7
    last_sync: '2017-11-15T17:56:32'
  ubuntu:12.04:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:12.04
    last_sync: '2017-11-15T17:55:57'
  ubuntu:12.10:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:12.10
    last_sync: '2017-11-15T17:56:19'
  ubuntu:13.04:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:13.04
    last_sync: '2017-11-15T17:56:37'
  ubuntu:14.04:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:14.04
    last_sync: '2017-11-15T17:56:15'
  ubuntu:14.10:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:14.10
    last_sync: '2017-11-15T17:55:42'
  ubuntu:15.04:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:15.04
    last_sync: '2017-11-15T17:55:44'
  ubuntu:15.10:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:15.10
    last_sync: '2017-11-15T17:56:17'
  ubuntu:16.04:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:16.04
    last_sync: '2017-11-15T17:55:34'
  ubuntu:16.10:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:16.10
    last_sync: '2017-11-15T17:56:06'
  ubuntu:17.04:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:17.04
    last_sync: '2017-11-15T17:56:20'
  ubuntu:17.10:
    access_tier: 0
    description: This group provides the vulnerability data for ubuntu:17.10
    last_sync: '2017-11-15T17:56:00'
name: vulnerabilities
subscribed: true
```
